config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'posts#index'

  resources :posts, only: %i[index show new create] do
    scope module: 'posts' do
      resources :comments, only: %i[create new]
      resources :likes, only: %i[create destroy]
    end
  end

  devise_for :users

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
  belongs_to :post_category
  belongs_to :creator, class_name: 'User'
  has_many :comments, class_name: 'PostComment', dependent: :destroy
  has_many :likes, class_name: 'PostLike', dependent: :destroy
end

app/models/post_category.rb
# frozen_string_literal: true

class PostCategory < ApplicationRecord
  validates :name, presence: true
  has_many :posts
end

app/models/post_comment.rb
# frozen_string_literal: true

class PostComment < ApplicationRecord
  validates :content, presence: true
  belongs_to :post
  belongs_to :user
  has_ancestry
end

app/models/post_like.rb
# frozen_string_literal: true

class PostLike < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, foreign_key: :creator
  has_many :likes, class_name: 'PostLike', dependent: :destroy
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/posts/comments_controller.rb
# frozen_string_literal: true

module Posts
  class CommentsController < ApplicationController
    before_action :authenticate_user!, only: %i[create new]
    before_action :post, only: :create

    # GET /posts/:post_id/comments/new
    def new
      @comment = PostComment.new(post_id: params[:post_id], parent_id: params[:parent_id])
    end

    # POST /posts/:post_id/comments
    def create
      @comment = @post.comments.build(comment_params.merge(user_id: current_user.id))
      if @comment.save
        redirect_to post_path(@post), notice: 'Comment was successfully created.'
      else
        render :new
      end
    end

    private

    def comment_params
      params.require(:post_comment).permit(:content, :parent_id)
    end

    def post
      @post ||= Post.find params[:post_id]
    end
  end
end

app/controllers/posts/likes_controller.rb
# frozen_string_literal: true

module Posts
  class LikesController < ApplicationController
    before_action :authenticate_user!, only: %i[create destroy]
    before_action :post, only: %i[create destroy]
    before_action :set_like, only: :destroy

    def create
      like = @post.likes.build(user_id: current_user.id)
      like.save
      redirect_to @post
    end

    def destroy
      @like.destroy
      redirect_to @post
    end

    private

    def set_like
      @like = PostLike.find(params[:id])
    end

    def post
      @post ||= Post.find params[:post_id]
    end
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create]
  before_action :set_post, only: :show

  # GET /posts
  def index
    @posts = Post.all.order(created_at: :desc)
  end

  # GET /posts/:id
  def show
    @comments = @post.comments
    @comment = @post.comments.build
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # POST /posts
  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :body, :post_category_id)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
  def nested_comments(comments)
    return if comments.nil?

    comments.map do |comment|
      render(partial: 'posts/comments/comment', locals: { comment: comment }) +
        content_tag(:div, nested_comments(comment.children), class: 'nested_comments')
    end.join.html_safe
  end
end

app/helpers/posts/comments_helper.rb
# frozen_string_literal: true

module Posts
  module CommentsHelper
    def nested_comments(comments)
      return if comments.nil?

      nested_comments = comments.map do |comment|
        render(partial: 'posts/comments/comment', locals: { comment: comment }) +
          content_tag(:div, nested_comments(comment.children), class: 'nested_comments')
      end
      safe_join(nested_comments)
    end
  end
end

app/helpers/posts/likes_helper.rb
# frozen_string_literal: true

module Posts
  module LikesHelper
    def user_liked_this_post?(post_id)
      return false if current_user.nil?

      current_user.likes.where(post_id: post_id).any?
    end
  end
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
  def days_ago_since(created_at)
    time_now = Time.now.getlocal
    creaton_on_date = Date.parse("#{created_at.day}/#{created_at.month}/#{created_at.year}")
    current_date = Date.parse("#{time_now.day}/#{time_now.month}/#{time_now.year}")
    current_date.mjd - creaton_on_date.mjd
  end
end

app/views/layouts/_nav.html.slim
nav.p-3.bg-dark.text-white
  .container
    .d-flex.flex-wrap.align-items-center.justify-content-center.justify-content-lg-start
      = link_to root_path, class: 'd-flex align-items-center mb-2 mb-lg-0 \
                                  text-white text-decoration-none' do
        i class='fas fa-home bi me-2'
      ul.nav.col-12.col-lg-auto.me-lg-auto.mb-2.justify-content-center.mb-md-0
        - if user_signed_in?
          li
            = link_to t('.new_post'), new_post_path, class: 'nav-link px-2 text-white'
          li
            = link_to t('.sign_out'), destroy_user_session_path, class: 'nav-link px-2 text-white',
                                                             method: :delete
        - else
          li
            = link_to t('.sign_in'), new_user_session_path, class: 'nav-link px-2 text-white'
          li
            = link_to t('.sign_up'), new_user_registration_path, class: 'nav-link px-2 text-white'

app/views/layouts/_navigation.html.slim
nav.navbar.navbar-dark.navbar-static-top.navbar-expand-md
  .container
    .collapse.navbar-collapse#bs-example-navbar-collapse-1
      ul.nav.navbar-nav.mr-auto
        li.nav-item
          = link_to 'Sign in', new_user_session_path, class: 'nav-link'
        li.nav-item
          = link_to 'Sign up', new_user_registration_path, class: 'nav-link'
        li.nav-item
          = link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link'

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      = t('.title')
    meta[name='viewport' content='width=device-width,initial-scale=1']
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag 'application', media: 'all',
                                         'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    header
      = render 'layouts/nav'
    - flash.each do |type, message|
      - case type
      - when 'notice'
        p.alert.alert-primary.text-center
          = message
      - when 'alert'
        p.alert.alert-danger.text-center
          = message
    = yield

app/views/posts/_form.html.slim
= simple_form_for(post) do |f|
  - if post.errors.any?
    #error_explanation

    h2[class='display-6']
      = pluralize(post.errors.count, 'error') + t('.error')
    ul
      - post.errors.each do |error|
        li
          = error.full_message
  = f.input :title
  = f.input :body
  = f.association :post_category, prompt: t('.select_post_category')
  = f.hidden_field :creator_id, value: current_user.id
  = f.button :submit, class: 'btn-default btn-primary my-3'

app/views/posts/comments/_comment.html.slim
b
  = comment.user.email
br
= comment.content
br
= link_to t('.reply'), new_post_comment_path(comment.post, parent_id: comment)

app/views/posts/comments/_form.html.slim
.container
  .row
    .col.col-md-6
      p
        strong
          = t('.new_comment_prompt')
      = simple_form_for(@comment, url: post_comments_path(@comment.post)) do |f|
        - if @comment.errors.any?
          #error_explanation

          h2[class='display-6']
            = pluralize(@comment.errors.count, 'error') + t('.error')
          ul
            - @comment.errors.each do |error|
              li
                = error.full_message
        = f.input :content, label: false
        = f.hidden_field :parent_id
        = f.button :submit, t('.create'), class: 'btn-default btn-primary'

app/views/posts/comments/new.html.slim
= render 'form'

app/views/posts/index.html.slim
.container
  h1[class='display-5']
    = t('.posts')
  ul.list-group.list-group-flush
    - @posts.each do |post|
      .row.list-group-item
        .col.col-md-6
          .row
            = link_to post.title, post
          .row
            = post.body
          .row
            | #{t('.likes')}: #{post.likes.count},
                #{days_ago_since(post.created_at)} days,
                #{post.creator.email}

app/views/posts/new.html.slim
.container
  .row
    .col.col-md-6
      h1[class='display-5']
        = t('.post')
      = render 'form', post: @post
      = link_to t('.back'), posts_path

app/views/posts/show.html.slim
.container
  h2[class='display-6']
    = @post.title
  .row
    .col.col-md-6
      p
        = @post.body
      p
        = "#{t('.posted_by')} #{@post.creator.email}, "
        - if user_liked_this_post?(@post)
          = link_to post_like_path(@post, @post.likes.where(post_id: @post.id).first),
                    method: :delete do
            i class='fas fa-thumbs-up'
        - else
          = link_to post_likes_path(@post), method: :post do
            i class='far fa-thumbs-up'
        = " #{@post.likes.count}"
    = render(partial: 'posts/comments/form', locals: { @comment => @comment })
  hr
  = nested_comments(@comments.select { |comment| !comment.has_parent? && comment.content })